[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
serde.workspace = true
serde_json.workspace = true
global_constants.workspace = true
humantime.workspace = true
humantime-serde.workspace = true
