[package]
name = "appstate"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
uuid.workspace = true
tracing = { workspace = true }
config.workspace = true
tokio.workspace = true
db = { workspace = true }
permissions = { workspace = true }
