[package]
name = "configman"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
config.workspace = true
tracing.workspace = true
serde_json.workspace = true
global_constants.workspace = true
