[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
colorlab = { workspace = true }
humantime = { workspace = true }
